### ISSUE TITLE
The CUDA code is not provided in the source code, can you provide it?CUDA code 

### ISSUE THREAD

**Issue by lzc17** [initzhang/DUCATI_SIGMOD#1]

**Comment by initzhang** [comment]
Hi, thank you for your interest in our work! 
Please read the first paragraph of README, we provided the relevant code in another repo. The recommended procedures to reproduce DUCATI are also provided. 
> We put the underlying implementations of some APIs in a customized version of DGL (https://github.com/initzhang/dc_dgl.git).
