### ISSUE TITLE
Testing the dc_dgl installation result prompts ''CUDA: an illegal memory access was encountered''

### ISSUE THREAD

**Issue by lzc17** [initzhang/DUCATI_SIGMOD#5]
![image](https://github.com/initzhang/DUCATI_SIGMOD/assets/41893135/12f07fb7-67ce-4ef4-86e9-9b3fca465e79)

**Comment by initzhang** [comment]
Hi, I have updated the script in the `dc_dgl` repo, could you try it again?

**Comment by initzhang** [comment]
https://github.com/initzhang/dc_dgl/issues/3
